### PR TITLE
Do not reformat Wiki-linked journal names

### PR DESCRIPTION
**Pull request by GlazerMann**
Fixes existing wiki-linked names getting formatted.  We just leave as-is.

### CODE REVIEW

**Comment by GlazerMann** [comment]
@ms609 When you have a chance.  Please look over the outstanding pulls and commit or comment.  I hope that they are all "outstanding" in both senses of the word.

**Comment by ms609** [comment]
My stance on this one is that there's never a time that a journal name should be wikilinked! This may be reflected in the template documentation on Wikipedia, or you could push for it... this must be an edge case!
Does the code handle piped links such as `[[ZooKeys (journal)| ZooKeys]]`?

**Comment by GlazerMann** [comment]
It does not handle that case.
I agree about wiki links to journals
Now that you mention it.  We should simply not touch them since who knows what’s in them.
I will update patch

**Comment by GlazerMann** [comment]
This now just gives up and does not try to format them at all if wiki-linked.  

Why do people do this?  I can think of one and only one reason to do that.  The journal is old and discontinued and thus has no ISSN, no DOI, no website, etc..  Then a wikilink to the journal is a good idea; and only then!

**Pull request merged**
