### PR TITLE
Rebasing soon

### PR DESCRIPTION
**Pull request by GlazerMann**
One API key for testing servers.  One for productions.  They are both restricted.

### CODE REVIEW

**Comment by GlazerMann** [comment]
Overly optimistic today.  Almost done/

**Comment by ms609** [comment]
Before rolling this out we'll probably need an API key
https://developers.google.com/books/docs/v1/using#auth

My current job (not that I've had any time to progress it for a while!) is to use OAuth to log the bot in to the WP servers, which might (?) help with authorizing requests once it's working.

**Comment by GlazerMann** [comment]
Need Google API key.  True.
URL needs this added
&key=yourAPIKey

**Comment by GlazerMann** [comment]
Obviously, the empty string “key” needs to be replaced with a real one

**Comment by GlazerMann** [comment]
The Google API key is set to only work on tools.wmflabs.org has address 208.80.155.131

**Comment by ms609** [comment]
I wonder how we can set up a test suite for this; we'd need to configure the API to work on Travis.
With other APIs I have one key that I put in the credentials folder on GitHub, and a separate key that I use for production (which I upload directly to the server and keep private).  Is this a possible solution?

**Comment by GlazerMann** [comment]
To get the API to work on travis, I just need to make another key that only works on travis IP addresses

**Comment by GlazerMann** [comment]
I think this ready to merge.

**Pull request closed without merging**
