### PR TITLE
Fall back to Semantic Scholar for OA URLs

### LINKED ISSUE #2475: Add SemanticScholar.org as a Citation Default Source
Following an initial conversation with @ms609 we are submitting a feature request to integrate the Citation Bot with Semantic Scholar's API (api.semanticscholar.org). In case you are not familiar with Semantic Scholar (semanticscholar.org), we are a free non-profit academic search and discovery engine developed by the Allen Institute for AI and over the past 4+ years we've developed a comprehensive literature graph that we provide programmatic access to with our API to advance open scientific search and discovery.

We are interested in adding our API as another data source to the Citation Bot in order to improve the availability of high quality links included in references in Wikipedia. Our API supports calls with DOIs and ArXiv IDs and we will be adding PubMed IDs next month. Here's the API call flow that we are proposing for the Citation Bot:

1. Citation Bot calls API with DOI/ArXiv ID/PubMed ID 
2. SemanticScholar API returns Paper/Title with "200" (Success Response) (let us know if paper title validation is sufficient to confirm that the referenced paper matches)
3. CitationBot creates a link from the title of the referenced work to the SemanticScholar paper detail page using our API redirect link structure (e.g. for a DOI-based link it looks like this: http://api.semanticscholar.org/10.1038/nrn3241)

Our goal is for these links to provide an additional discovery entry point for Wikipedia users so that they can explore our literature graph and find additional relevant information. You can find an example of one of our paper detail pages here: https://www.semanticscholar.org/paper/%22Why-Should-I-Trust-You%22%3A-Explaining-the-of-Any-Ribeiro-Singh/5091316bb1c6db6c6a813f4391911a5c311fdfe0.
Please let us know if this would be a useful enhancement for the Citation Bot and if yes, we are happy to have our developers submit a code change for approval (if that's the easiest way to proceed)

### PR DESCRIPTION
**Pull request by milescrawford**
Creating this request just to get tests to run.

Fixes #2475

Changes implemented in this pull request:
- If Unpaywall does not provide a useful Open Access URL, fall back to Semantic Scholar

### CODE REVIEW

**Comment by milescrawford** [comment]
Tests seem broken, I'll try to figure out how to get them running locally, outside of travis.

**Comment by milescrawford** [comment]
Travis build output does not include the specific tests that failed, or the error messages.

**Comment by GlazerMann** [comment]
Please look again at new log

**Comment by GlazerMann** [comment]
You forgot the $this->

**Comment by milescrawford** [comment]
Thank you, I have them running locally as well :)

**Comment by GlazerMann** [comment]
Some tests seem to be failing now for unrelated reasons.   Double check return codes and setting of function local variables that don’t get passed out

**Comment by milescrawford** [comment]
Thanks will pick this up on monday.

**Comment by GlazerMann** [comment]
In the main branch:  I fixed some issues with non-project-member pull requests.   I also split a bunch of the tests into a bunch of smaller tests.   These have all been pushed into your branch

**Comment by milescrawford** [comment]
@GlazerMann Tests passing!

**Comment by GlazerMann** [comment]
And now the political battle.  I guess the copyright police are not happy with us adding the links we already do.  https://en.wikipedia.org/wiki/User_talk:Citation_bot#Semantic_scholar

**Comment by skohlmeier** [comment]
@GlazerMann - Thank you for bringing the conversation to our attention! We'll respond shortly to provide additional background information (we have indexing partnerships with 550+ publishers and academic societies that provide us with full text) and clarify how we crawl and what our policies are.

**Comment by GlazerMann** [comment]
https://en.wikipedia.org/wiki/User_talk:Citation_bot/Archive_13#Do_not_automatically_add_Citeseerx

**Comment by skohlmeier** [comment]
@GlazerMann thank you for linking to the CiteSeer discussion. That helps add good context and here's what we plan to do to fulfill copyright requirements for linking:

- Add an "is_publisher_licensed" boolean flag to our API to indicate when a paper has been provided/officially licensed to us for indexing by one of our 550+ publishers and academic societies
- Add logic to only insert links in the Citation Bot if the flag is set to ensure that we are linking only to licensed content (this will prevent links to content that was crawled)

Let me know if you think that this will be sufficient to satisfy Wikipedia requirements and address the concerns that have been highlighted.

**Comment by GlazerMann** [comment]
I think that is good enough.

**Comment by GlazerMann** [comment]
I made some changes.  The OA search no longer with return your URLS.  Those will be rejected in case they are "unlicenced" so that your api can search the.

**Comment by skohlmeier** [comment]
Thanks for confirming! We will go ahead and add the "is_publisher_licensed" flag to our API and will update this pull request accordingly.

**Comment by milescrawford** [comment]
@GlazerMann The update is made and tests are passing - we now only insert a semanticscholar link if the article is covered by one of our publisher contracts/licenses.

**Pull request merged**
