### PR TITLE
add jstor support using Citoid

### PR DESCRIPTION
**Pull request by GlazerMann**
Fixes missing jstor support
Includes test case

### CODE REVIEW

**Comment by GlazerMann** [comment]
Not fully baked yet.  But, open for comments

**Comment by GlazerMann** [comment]
incompleteBook() is not actually used at this time.

**Comment by GlazerMann** [comment]
Jstor has added more stuff.  The SICI link now points to 25 articles.  I will fix.   That is why SICI links need fixed

**Comment by GlazerMann** [comment]
https://github.com/zhaofengli/refill/blob/11ef3b3b35bcd686ffd5aacb9c2dafe9dbf8e5e1/src/Reflinks/LinkHandlers/CitoidLinkHandler.php

This points to reFill parsing code.  Just found it.

**Comment by ms609** [comment]
Great job, lovely to have JSTOR supported again!
Could you add a test case that adds authors to a journal too, please? These parameters are often particularly irksome so worth checking that they are covered.

**Pull request merged**
