### PR TITLE
Do edits as BOT account

### PR DESCRIPTION
**Pull request by GlazerMann**

### CODE REVIEW

**Comment by davidbarratt** [comment]
I'm not sure how this is necessary? The edit will be made the by user who invoked the bot.

**Comment by pppery** [comment]
There's some (in my opinion meritless) complaining going on on-wiki about the edits being attributed to the user.

**Comment by GlazerMann** [comment]
There is currently a firestorm on en.wikipedia.org about user's accounts being used instead of the  bot's account.  I just fanned the flames.  Soryy, not sorry.

**Comment by davidbarratt** [comment]
> There is currently a firestorm on en.wikipedia.org about user's accounts being used instead of the bot's account. I just fanned the flames. Soryy, not sorry.

Could you provide a link to the discussion? Thanks!

**Comment by pppery** [comment]
https://en.wikipedia.org/wiki/User_talk:Citation_bot#Need_to_use_user_OAuth (the bottom of the thread)

**Comment by davidbarratt** [comment]
Here's the discussion around why this direction was chosen: https://phabricator.wikimedia.org/T225675 we could change this to imploy OAuth and then check to see if the user is blocked from the page before editing under the bot's account.

**Comment by davidbarratt** [comment]
As an example, An API Request like this:
https://en.wikipedia.org//w/api.php?action=query&format=json&prop=info&titles=Oulu%20University%20Hospital&formatversion=2&intestactions=edit
will tell you if the current user can `edit` the specific page (under `actions`, `edit`).

**Comment by GlazerMann** [comment]
closing but not deleting

**Pull request merged**
