### PR TITLE
echo vs. print.  die vs. exit

### PR DESCRIPTION
**Pull request by GlazerMann**
Never use die or print in production code
All die and print removed

### CODE REVIEW

**Comment by GlazerMann** [comment]
I think I got all of them.  Some are a matter of opinion

**Comment by GlazerMann** [comment]
I am done with this.  Please commit or comment.

**Comment by ms609** [comment]
In practice I think the distinction is too arbitrary - I think perhaps we should use `echo` and `exit` throughout.  I think this is actually closer to my original intention in any case -- I use `print` and `die` to throw debugging messages, so can search for these terms before making a commit to make sure I've not left any in.  Hope that's okay?

**Comment by GlazerMann** [comment]
Are any of these categorized wrong?

**Comment by GlazerMann** [comment]
I believe that this is now every die and print statement.

**Pull request merged**
