### PR TITLE
Do not add banned urls

### PR DESCRIPTION
**Pull request by GlazerMann**
we can’t save if we add these
these are from non-cross-ref doi's

### CODE REVIEW

**Comment by josve05a** [comment]
Perhaps to future-saving ourself, we should perhaps make a copy of (or fetch) the official blacklist of links. In case more links are to be banned, or for when this is removed from the blacklist.

**Comment by GlazerMann** [comment]
There are actually multiple ever changing blacklists.  Do you know a good way to find them?

**Comment by josve05a** [comment]
https://en.wikipedia.org/wiki/MediaWiki:Spam-blacklist is the main one

**Comment by GlazerMann** [comment]
Fixed elsewhere in code

**Pull request closed without merging**
