### PR TITLE
This only works for ms609

### PR DESCRIPTION
**Pull request by GlazerMann**
this code runs on the pull request but the script dies a 99 and cannot go on
Sleep so that the code has time for the update to patch the patch 
I am surprised that the code exists with 99 but somewhere somehow the code gets patched

### CODE REVIEW

**Comment by ms609** [comment]
Maybe that's why it's an exit 0 by default.  Does it work without the sleep?

**Comment by GlazerMann** [comment]
I am not sure.   Sleep is paranoia

**Comment by GlazerMann** [comment]
I am concerned the next test will run before the update

**Comment by GlazerMann** [comment]
I saw this in the capitals pull.   “You” edited my pull

**Comment by ms609** [comment]
If the 99 code occurs, then presumably no pull is going to occur, as the script is exiting with failure instead of using the GITHUB_PAT?

**Comment by ms609** [comment]
The idea is that small words can be added and will be sorted alphabetically by Travis as part of the build sequence.  This makes duplication easier to spot, and saves lists getting out of order.
Of course, it may be the case that this 'innovation' ends up causing more trouble than it saves...

**Comment by GlazerMann** [comment]
I cannot seem to set the GitHub Pat for me in this repository.
Also, the script insists on setting itself to be you so I don’t know of that matters anyway

**Comment by GlazerMann** [comment]
Maybe the sleep is not needed if the commit changes the code and makes Travis run again

**Pull request closed without merging**
