### PR TITLE
fix ZooKeys better

### PR DESCRIPTION
**Pull request by GlazerMann**
Really need to return before adding volume

### CODE REVIEW

**Comment by ms609** [comment]
Probably ought to use add_if_new to be safe - in case someone has manually filled the 'issue' parameter with a comment, for example.
Might the code also be clearer if you used the syntax "if (zookeys) add_if_new(issue) **else** add ($param)"?

**Comment by GlazerMann** [comment]
O think it is better now.  Can't believe I misspelled zookeys.

**Comment by GlazerMann** [comment]
One more note.  You might want to delete the branch labeled "wiki".  It has only one file.  Also, the branch labeled "dev" is very out of date.  I assume that it should go too.

**Comment by GlazerMann** [comment]
NOW I am done.  Very sorry about that.

One more note. You might want to delete the branch labeled "wiki". It has only one file. Also, the branch labeled "dev" is very out of date. I assume that it should go too.

**Comment by ms609** [comment]
Sounds good - will the case of ZooKeys always match what you have written or might it ever be "Zookeys"? A case insensitive match would be appropriate in the latter case.  Will merge for now in any case.

**Pull request merged**
