### PR TITLE
Catch more bare DOI citations and send them to cleanup

### PR DESCRIPTION
**Pull request by nemobis**

### CODE REVIEW

**Comment by ms609** [comment]
Thanks for the pull request; it'd be really handy if you could add some tests to the test suite that will invoke the code you've written; i.e. dois that fail under the existing code that will be handled correctly under your proposal.

**Comment by nemobis** [comment]
I agree, I was about to post some examples: https://phabricator.wikimedia.org/P8007
Do you have suggestions on which ones to include?

**Comment by GlazerMann** [comment]
We should have at least one for each Regex

**Comment by GlazerMann** [comment]
<ref>John Doe, [https://doi.org/10.1244/abc Foo], Bar 1789.</ref> regex is messed up.  I fixed some issues, but not all

**Comment by GlazerMann** [comment]
I cancelled the 5.6 build since we have more code to write

**Comment by GlazerMann** [comment]
I added a bunch of tests.  They all will fail, since I do not know the output yet.

**Pull request merged**
