### PR TITLE
I believe this needs to go after UTF-8 stuff

### PR DESCRIPTION
**Pull request by GlazerMann**
It is not doing its job where it is now.

### CODE REVIEW

**Comment by ms609** [comment]
Has the fix been tested?

**Comment by GlazerMann** [comment]
This fix has NOT been tested.  Off course, it probably needs changed in  format_title_text_nocaps() if that is added as per your previous comment.

**Comment by GlazerMann** [comment]
I apologize.  I seem to be targeting master, not development branch.  Now master is ahead of devel :-(

**Comment by ms609** [comment]
Looks to me like the following lines (`$iIn`, `$iOut`) might also belong in sanitize_string?  As it stands, there is some duplication: a pipe `|` will be `&#ed;` before it is `{{!}}`ed.

**Comment by GlazerMann** [comment]
Updated.  You are right.  pipe to {{!}} to escaping is bad.

**Pull request merged**
