### PR TITLE
Deal with URLs as Journal names

### PR DESCRIPTION
**Pull request by GlazerMann**
This fixes us from making garbage input even worse.

### CODE REVIEW

**Comment by ms609** [comment]
Two musings:
- Are the test cases legitimate input that ought to be supported by Cite journal etc?  Seems to me like this behaviour might be caught under GIGO.
- This seems like a heavy-handed approach.  Better (if perhaps unduly complicated?) would be to support URLs in `title_capitalization` -- i.e. to include a regexp in the function that allows parts of the string that SHOULD be capitalized to be so. 
e.g. `[http://journalofmedicine.com journal of medicine]` → `[http://journalofmedicine.com *J*ournal of *M*edicine]`

**Comment by GlazerMann** [comment]
It is really GIGO.  We just do not want to make it worse.
I have never actually seen the [htt....] case.

**Comment by GlazerMann** [comment]
I think I need to change is so that if we find www... then we rename publisher to website and if we find http.... we rename it to url

**Comment by GlazerMann** [comment]
@ms609 How about this?

**Pull request merged**
