### PR TITLE
Older PHP does not support const arrays.

### PR DESCRIPTION
**Pull request by GlazerMann**
Probably better to update PHP on Wiki Tools to match test environment.

### CODE REVIEW

**Comment by GlazerMann** [comment]
Seems to me that the test environment might need to match the Wiki PHP version.

**Comment by ms609** [comment]
Oh dear - I'd assumed (hoped) that wmflabs were running PHP7.  The code will require some significant refactoring otherwise - you can't `define` arrays either, so we'd have to go back to using global variables (strongly discouraged).  Can we explore what it would take for wmflabs to upgrade to php7?  It might be as simple as re-naming files to the .php7 suiffix, if they have that version installed

**Comment by GlazerMann** [comment]
It is 5.5.9. 

Old 👵🏻👴🏻

**Comment by ms609** [comment]
That's frustrating. What is the prospect of them upgrading to PHP7?  For now, I've added 5.5.9 to the Travis test cases, but it will take some work to re-adapt the code; probably the thing to do is to make a public function `const_array($name)` that returns the array required, and replace all calls to the constant arrays with a call to the function.  I've no time to do that myself at the moment; feel free to have a shot yourself if that sounds easier than pushing for a PHP version upgrade at WMFlabs!

**Comment by GlazerMann** [comment]
Fighting this issue in wiki land

**Comment by GlazerMann** [comment]
5.6 is supported sort of. Check Wikipedia talk page.

**Comment by ms609** [comment]
I believe that PHP7 is the first version to allow const arrays.

**Comment by GlazerMann** [comment]
Actually 5.6 supports it.  It appears that it was considered useful enough to add.  That’s the last pre-7 version.

**Comment by ms609** [comment]
Oh, great!  Are you able to see what is needed to force the use of this
version?

--

*Martin R. Smith*
Assistant Professor in Palaeontology
Department of Earth Sciences
Durham University
Mountjoy Site, South Road
Durham DH1 3LE

*T*: +44 191 334 2320
*M*: +44 774 353 7510
*E*: martin.smith@durham.ac.uk
*Skype*: martin--smith

durham.ac.uk/earth.sciences/staff/academic/?id=14260
twitter.com/PalaeoSmith

The information in this e-mail and any attachments is confidential. It is
intended solely for the addressee or addressees. If you are not the
intended recipient please delete the message and any attachments and notify
the sender of mis-delivery. Any use or disclosure of the contents of either
is unauthorised and may be unlawful.
Although steps have been taken to ensure that this e-mail and any
attachments are free from any virus, we advise the recipient to ensure they
are indeed virus free. All liability for viruses is excluded to the fullest
extent permitted by law.

**Comment by GlazerMann** [comment]
https://wikitech.wikimedia.org/wiki/Help:Toolforge/Kubernetes#Versions_.26_Packages

Yeah it means using a container.   It’s not just a flag.  This discussion is probably better on Wikipedia

**Comment by kaldari** [comment]
@GlazerMann: Something seems to be messed up with the Kubernetes set up on Toolforge. I haven't been able to get it running at all.

**Comment by GlazerMann** [comment]
The dev code does not work as far as I can tell.  What types of errors do you get.  As a user, we do not see the erros

**Comment by GlazerMann** [comment]
Once we have the error messages; we can fix PHP Code to work with 5.6

**Comment by ms609** [comment]
Even in PHP 5.6, constants must evaluate to scalar values: see
https://travis-ci.org/ms609/citation-bot/jobs/281183252

Looks like the code will have to be refactored.  This might be something I can have a bash at today.

**Comment by ms609** [comment]
Please direct any further discussion on this topic to the related [issue](https://github.com/ms609/citation-bot/issues/177).

**Pull request closed without merging**
