### PR TITLE
Support for Vancouver list style specified via a template on the page (similar to {{Use dmy dates}} template)

### PR DESCRIPTION
**Pull request by maximmasiutin**
If the page contains `{{Use vanc name-list-style}}` template, then it uses `|vauthors=` and `|veditors=` attributes rather than firstN/lastN and editor-firstN/editor-lastN. This is similar to `{{Use dmy dates}}` template when the Citation Bot uses date format as specified on the page. To reproduce this behaviour, edit a page on Wikipedia, add `{{Use vanc name-list-style}}` template (or `{{Use vanc name-list-style|date=December 2023}}`), delete author names (firstN/lastN) and run the bot. It will fill the names as vauthors.

Update: there is a discussion at https://en.wikipedia.org/wiki/User_talk:Citation_bot#Specifying%20name%20list%20style%20for%20newly-added%20name%20entries
on what template to use as a hint.

### CODE REVIEW

**Comment by GlazerMann** [comment]
changing the existing authors will get the bot banned.

**Comment by maximmasiutin** [comment]
> changing the existing authors will get the bot banned.

It does not change existing authors. It only fills the authors if they are missing and if there is a template {{Use vanc name-list-style}}, at least this is intended.

**Comment by maximmasiutin** [comment]
So for the newly-filled authors, this variable is used to select style on filling the author list.

**Comment by maximmasiutin** [comment]
Currently almost all articles on molecular biology and medicine use the name list style `|vauthors=`
See examples at:
* https://en.wikipedia.org/wiki/Archaea
* https://en.wikipedia.org/wiki/Bacteria
* https://en.wikipedia.org/wiki/DNA
* https://en.wikipedia.org/wiki/Enzyme

So it is a common style; no need to change anything, just use it for new refs on a page that has a template {{Use vanc name-list-style}}

**Comment by maximmasiutin** [comment]
@GlazerMann - maybe you have an idea how to implement that faster.

There is a function in Template.php:
```
  protected function join_params() : string {
    if (self::$name_list_style === NAME_LIST_STYLE_VANC)
```

If should be an additional condition that the citation had no names specified and the names were taken from online database, as an additional condition for that, such as $names_were_empty?

**Comment by maximmasiutin** [comment]
There are $had_initial_editor and $had_initial_publisher and $no_initial_doi, but a similar for the authors should be useful

**Comment by maximmasiutin** [comment]
I will try to use `initial_author_params`

**Comment by maximmasiutin** [comment]
I made the required change and not it only fills the vauthors parameter if no authors or editors were filled and {{Use vanc name-list-style}} was set.

**Comment by GlazerMann** [comment]
Please add some tests to the Template tests.

**Comment by maximmasiutin** [comment]
> Please add some tests to the Template tests.

Thank you, let me do that!

**Comment by maximmasiutin** [comment]
I tried to make tests work but didn't figure out how did they expand citations; expansion only worked to me if I run the software, not on tests. Could you please add those pages to tests, because, as with time, expansion depends on a config template used on the page:

# The authors expanded by default to first1/last1
input page:
`{{Use dmy dates|date=December 2023}}<ref>{{cite journal | title = The microRNA miR-184 regulates the CYP303A1 transcript level to control molting of Locusta migratoria | journal = Insect Science | date = June 2020 | volume = 28 | issue = 4 | pages = 941–951 | pmid = 32524775 | doi = 10.1111/1744-7917.12837 | s2cid = 219588137 }}</ref>`
output page:
`{{Use dmy dates|date=December 2023}}<ref>{{cite journal | title = The microRNA miR-184 regulates the CYP303A1 transcript level to control molting of Locusta migratoria | journal = Insect Science | date = June 2020 | volume = 28 | issue = 4 | pages = 941–951 | pmid = 32524775 | doi = 10.1111/1744-7917.12837 | s2cid = 219588137 | last1 = Wang | first1 = Yan‐Li | last2 = Wu | first2 = Li‐Xian | last3 = Li | first3 = Hui‐Yong | last4 = Wen | first4 = Xue‐Qin | last5 = Ma | first5 = En‐Bo | last6 = Zhu | first6 = Kun‐Yan | last7 = Zhang | first7 = Jian‐Zhen }}</ref>`

# On a page with {{Use vanc name-list-style}} template the authors expanded to vauthors
input page:
`{{Use vanc name-list-style|date=December 2023}}<ref>{{cite journal | title = The microRNA miR-184 regulates the CYP303A1 transcript level to control molting of Locusta migratoria | journal = Insect Science | date = June 2020 | volume = 28 | issue = 4 | pages = 941–951 | pmid = 32524775 | doi = 10.1111/1744-7917.12837 | s2cid = 219588137 }}</ref>`
output page:
`{{Use vanc name-list-style|date=December 2023}}<ref>{{cite journal | title = The microRNA miR-184 regulates the CYP303A1 transcript level to control molting of Locusta migratoria | journal = Insect Science | date = June 2020 | volume = 28 | issue = 4 | pages = 941–951 | pmid = 32524775 | doi = 10.1111/1744-7917.12837 | s2cid = 219588137 | vauthors = Wang Y, Wu L, Li H, Wen X, Ma E, Zhu K, Zhang J }}</ref>`

# When the auhors are already expanded, they don't change, no matter what tempalte we use:
Input page:
`{{Use vanc name-list-style|date=December 2023}}<ref>{{cite journal | title = The microRNA miR-184 regulates the CYP303A1 transcript level to control molting of Locusta migratoria | journal = Insect Science | date = June 2020 | volume = 28 | issue = 4 | pages = 941–951 | pmid = 32524775 | doi = 10.1111/1744-7917.12837 | s2cid = 219588137 | last1 = Wang | first1 = Yan‐Li | last2 = Wu | first2 = Li‐Xian | last3 = Li | first3 = Hui‐Yong | last4 = Wen | first4 = Xue‐Qin | last5 = Ma | first5 = En‐Bo | last6 = Zhu | first6 = Kun‐Yan | last7 = Zhang | first7 = Jian‐Zhen }}</ref>`
Output page:
`{{Use vanc name-list-style|date=December 2023}}<ref>{{cite journal | title = The microRNA miR-184 regulates the CYP303A1 transcript level to control molting of Locusta migratoria | journal = Insect Science | date = June 2020 | volume = 28 | issue = 4 | pages = 941–951 | pmid = 32524775 | doi = 10.1111/1744-7917.12837 | s2cid = 219588137 | last1 = Wang | first1 = Yan‐Li | last2 = Wu | first2 = Li‐Xian | last3 = Li | first3 = Hui‐Yong | last4 = Wen | first4 = Xue‐Qin | last5 = Ma | first5 = En‐Bo | last6 = Zhu | first6 = Kun‐Yan | last7 = Zhang | first7 = Jian‐Zhen }}</ref>`

**Comment by GlazerMann** [comment]
I will be away from my desk for a couple days.  Some of "Bot Full Test Suite" tests are broken and some work only half the time.  That's a problem with tests that depends upon others.

**Comment by maximmasiutin** [comment]
The changes that I suggested should not affect the tests, as they only introduce new functionality when the new templates are used. I wonder why the tests are broken. Is there any todo-list on how should I properly run those tests locally?

**Comment by maximmasiutin** [comment]
> I will be away from my desk for a couple days. Some of "Bot Full Test Suite" tests are broken and some work only half the time. That's a problem with tests that depends upon others.

I fixed the two character conversion tests that failed on the server, and made one test fail verbose (with Google Book dates).

However, those character conversion tests are incorrectly written, you cannot convert immediate string literals that way. If you wish, I will change the other 3 conversion tests same way, because they may also fail should something change in configuration.

As for the data requests, I suggest you to configure GitHub API, maybe it will not fail. I don't know why it doesn't request data for some tests. I didn't request in my case also.

**Comment by maximmasiutin** [comment]
There is a discussion at https://en.wikipedia.org/wiki/User_talk:Citation_bot#Specifying%20name%20list%20style%20for%20newly-added%20name%20entries on which template to support. Please let the discussion come to a consensus.

**Comment by maximmasiutin** [comment]
@GlazerMann - can you please approve the pull request, as we reached consensus on Wikipedia on this feature, see https://en.wikipedia.org/wiki/User_talk:Citation_bot#Specifying%20name%20list%20style%20for%20newly-added%20name%20entries

**Comment by GlazerMann** [comment]
There is an error with a typo.  The static tests found it.

**Comment by GlazerMann** [comment]
You asked about this line " // $cache_bad[$doi] = TRUE; do not store to save memory". The reason those are not cached, is because they are cached in the dx.doi.org check, so there is no need to cache the faile in the crossref check array.

**Comment by GlazerMann** [comment]
I changed:
if (is_string($tfk) && (strlen($tkf) > 0)) {
to 
if (is_string($tfk) && (strlen($tfk) > 0)) {

**Comment by maximmasiutin** [comment]
Oops, sorry, let me retest that. I tested, but then fixed a style error and not retested.

**Comment by maximmasiutin** [comment]
@GlazerMann  -- I've just checked it and it works properly.

```
citation-bot % php ./process_page.php "CYP303A1" --slow --savetofiles
```

It should save the file CYP303A1.md, and if you compare it with the original content, it will contain vauthors attributes added, such as `| vauthors = Wu L, Jia Q, Zhang X, Zhang X, Liu S, Park Y, Feyereisen R, Zhu KY, Ma E, Zhang J, Li S`, etc.

Now it should be OK. Please see https://en.wikipedia.org/wiki/CYP303A1 for the sample code that when the bot processes, should add vauthors  rather than first1/last1 etc.

**Comment by maximmasiutin** [comment]
> You asked about this line " // $cache_bad[$doi] = TRUE; do not store to save memory". The reason those are not cached, is because they are cached in the dx.doi.org check, so there is no need to cache the faile in the crossref check array.

Can you please add a source code comment that explains that, as it was not quite clear why that was commented.

**Comment by GlazerMann** [comment]
I added a bunch of tests and fixed some bugs

**Comment by maximmasiutin** [comment]
> I added a bunch of tests and fixed some bugs

How can I test them?

**Comment by GlazerMann** [comment]
Test are in test suite and run as part of the "Bot Full Test Suite".

**Comment by GlazerMann** [comment]
Please verify that tests looks correct.  I have included some extra stuff such a {{!}} to make sure that the test is bit more like a real page.

**Comment by GlazerMann** [comment]
The tests all need changed.  The DOI is not in crossref, so the tests are unreliable.

**Comment by maximmasiutin** [comment]
I've tried the updated master on the CYP303A1 page at Wikipedia and it works correctly, thank you very much! Should I review something else, please let me know.

**Pull request merged**
