### PR TITLE
parse_text() is called many places

### PR DESCRIPTION
**Pull request by GlazerMann**
parse_text() restarts a zero, and that seems like a bad idea since it is called all over the place

### CODE REVIEW

**Comment by GlazerMann** [comment]
Obviously not getting unwrapped either enough 😲

Might also want two dimensional array where encoding and decoding is a stack.

**Comment by GlazerMann** [comment]
I have a test case, but no solution.

**Comment by ms609** [comment]
Wouldn't the internal comments have been replaced by placeholders when the page was parsed?  `process_page` should be used instead of `process_citation` here.  Unfortunately that makes the test cases a little more complicated.
```php
$text = '{{Cite journal|url={{This is not real}} | doi = {{I am wrong}} |jstor= {{yet another bogus one }}  }}';
       $expanded = $this->process_page($text);
       print $expanded->parsed_text();
```

**Comment by GlazerMann** [comment]
Comments seem to be okay.   It is templates that do not make it out alive.

Happens with real pages too.

**Comment by ms609** [comment]
Seems to be passing okay in a hasty test but I'll look into this properly anon.

**Comment by GlazerMann** [comment]
Closing and pointing to other open pull

**Pull request closed without merging**
