### PR TITLE
Red Alert:  Location and publisher gets to stay

### PR DESCRIPTION
**Pull request by GlazerMann**
the RFC went our way mostly, but not quite enough for a bot to do the work

### CODE REVIEW

**Comment by Sky2042** [comment]
"You should probably remove" is not really appropriate given the close of the RFC.

**Comment by GlazerMann** [comment]
The close was that it was probably best to remove them; but, by hand since is rare cases they would be information

**Comment by Sky2042** [comment]
> text changed to informative instead of prescriptive

That looks pretty reasonable to me.

**Comment by GlazerMann** [comment]
@Sky2042 thank you.  I commented on the talk page too.  We shall see.

**Pull request merged**
