### PR TITLE
add one more journal

### PR DESCRIPTION
**Pull request by GlazerMann**

### CODE REVIEW

**Comment by ms609** [comment]
Should there be a space before the "Historical"?  
More generally, is there any merit in implementing the rule "always capitalize the letter after a colon"?  This might help to reduce the number of manual exceptions that we must specify.

**Comment by GlazerMann** [comment]
Fixed.  You are right about needing a more general fix.  Merge this and we can do general fix soon

**Comment by ms609** [comment]
Currently failing constantsTest::testConstantsDefined:
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-' Historical Biology: An International Journal of Paleobiology '
+' Historical Biology: An International Journal Of Paleobiology '

**Comment by GlazerMann** [comment]
It now works.
Another more general pull exists too now

**Pull request merged**
