### PR TITLE
Do not flag placeholders as bad DOIs

### PR DESCRIPTION
**Pull request by GlazerMann**
Do not flag placeholders as bad DOIs

### CODE REVIEW

**Comment by ms609** [comment]
To reduce the risk of false positives, would it be better to look for a match with the placeholders themselves?
`sprintf(PLACEHOLDER, '\d+')` will convert a placeholder to a regular expression.  Or it shouldn't be too tricky to write a regexp that would catch the exisitng placeholder formats.

**Comment by ms609** [comment]
Looking at this again, it looks like what we really want to do is to strip out any placeholders at the point of reading the DOI.  So a DOI reading `doi = 10.1038/nature12345<!--here is a comment-->` should have the comment removed before being treated normally.

**Comment by GlazerMann** [comment]
0. trim()
1.  Look for # # ........... # # start and end.
2.  Remove and save it to a temporary string AND remember if start or end
3.  Look for another one, if another one then abort.  This is paranoia.
4.  Process DOI
5.  Re-add # # ............ to front and back as needed.

**Comment by ms609** [comment]
I was thinking more along the lines of
```php
$doi = preg_replace_all($placeholder_format, '', $this->get('doi'));
if (doi_is_broken($doi)) {
  $this->set('doi_broken_date');
}
```

**Comment by GlazerMann** [comment]
The Bot documentation states that if the doi parameter is comment (and just a comment), then bot will not fill it.  That way you can block an invalid DOI.  So, should we remove that documentation?

**Comment by GlazerMann** [comment]
All the changes are in one location now.  A single function that was already being used get_without_comments.

**Comment by GlazerMann** [comment]
Interesting.  The template placeholder does not get Un-Escaped

**Comment by GlazerMann** [comment]
This is ready to go

**Comment by GlazerMann** [comment]
We are good to go!!!!!!

**Comment by GlazerMann** [comment]
Thank you for explanation of how to properly test this as a page, and not a template

**Comment by GlazerMann** [comment]
Please push this on in now.

**Pull request merged**
