### PR TITLE
copy over some dev changes that worked

### PR DESCRIPTION
**Pull request by GlazerMann**
Formatting title text basically everywhere seems to have fixed the failure to escape evil square braces etc in titles.

### CODE REVIEW

**Comment by ms609** [comment]
Do you have a brief example that would reproduce the bug? Sounds like it would be a useful addition to the suite of test cases I am developing.

**Comment by ms609** [comment]
And is this basically a request to update the master branch from the development branch?  Starting a pull request from the development branch might be a more appropriate way to do that.

**Comment by GlazerMann** [comment]
https://en.wikipedia.org/wiki/User:AManWithNoPlan/sandbox2

Lots of test cases

**Comment by GlazerMann** [comment]
This is basically a request to update master from devel.  Did not do pull from dev, since I am still figuring out GUI.

**Comment by ms609** [comment]
It does take some gettting used to.  At https://github.com/ms609/citation-bot, you want to select Branch:development from the dropdown above the list of files, then click `New pull request` to pull from development into master.  That way the 'edit history' is preserved.

**Comment by ms609** [comment]
I've implemented some of your test cases in the continuous integration suite (see in particular tests/phpunit/TemplateTests.php), so if any future edits cause the errors to recur, they should be flagged right away.
I won't have the time myself, but you might think about incorporating further salient examples from your test suite; let me know if you need a hand figuring out how.

**Pull request closed without merging**
