### PR TITLE
Journal Italics - add test

### PR DESCRIPTION
**Pull request by GlazerMann**

### CODE REVIEW

**Comment by GlazerMann** [comment]
This is a bug in Dev branch

**Comment by ms609** [comment]
Looks like it thinks it's a species, from the taxon matching regexp in format_title_text [sp?].  Perhaps we need to drop those lines in format_title_test, only call them if it's a new title, or add a capitalization exclusion for that particular journal.

**Comment by GlazerMann** [comment]
It seems to be any internal capitalization causes this.

**Comment by GlazerMann** [comment]
$p->val = format_title_text(title_capitalization($p->val, FALSE, FALSE));
    

In tidy()

**Pull request closed without merging**
